#!/bin/bash

export DOTNET_REFERENCE_ASSEMBLIES_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5

cd Web

dotnet restore -r osx-x64
dotnet build -r osx-x64

mono --arch=64 --debug bin/Debug/net462/Web.exe
